//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace sparc.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SARCFACIN2Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SARCFACIN2Entities object using the connection string found in the 'SARCFACIN2Entities' section of the application configuration file.
        /// </summary>
        public SARCFACIN2Entities() : base("name=SARCFACIN2Entities", "SARCFACIN2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SARCFACIN2Entities object.
        /// </summary>
        public SARCFACIN2Entities(string connectionString) : base(connectionString, "SARCFACIN2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SARCFACIN2Entities object.
        /// </summary>
        public SARCFACIN2Entities(EntityConnection connection) : base(connection, "SARCFACIN2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sparc_Aulas> sparc_Aulas
        {
            get
            {
                if ((_sparc_Aulas == null))
                {
                    _sparc_Aulas = base.CreateObjectSet<sparc_Aulas>("sparc_Aulas");
                }
                return _sparc_Aulas;
            }
        }
        private ObjectSet<sparc_Aulas> _sparc_Aulas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sparc_Aulas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosparc_Aulas(sparc_Aulas sparc_Aulas)
        {
            base.AddObject("sparc_Aulas", sparc_Aulas);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SARCFACIN2Model", Name="sparc_Aulas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sparc_Aulas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sparc_Aulas object.
        /// </summary>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="horário">Initial value of the Horário property.</param>
        /// <param name="atividade">Initial value of the Atividade property.</param>
        /// <param name="turma">Initial value of the Turma property.</param>
        /// <param name="disciplina">Initial value of the Disciplina property.</param>
        /// <param name="professor">Initial value of the Professor property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="aulaId">Initial value of the AulaId property.</param>
        public static sparc_Aulas Createsparc_Aulas(global::System.DateTime data, global::System.String horário, global::System.String atividade, global::System.Int32 turma, global::System.String disciplina, global::System.String professor, global::System.Guid userId, global::System.Guid aulaId)
        {
            sparc_Aulas sparc_Aulas = new sparc_Aulas();
            sparc_Aulas.Data = data;
            sparc_Aulas.Horário = horário;
            sparc_Aulas.Atividade = atividade;
            sparc_Aulas.Turma = turma;
            sparc_Aulas.Disciplina = disciplina;
            sparc_Aulas.Professor = professor;
            sparc_Aulas.UserId = userId;
            sparc_Aulas.AulaId = aulaId;
            return sparc_Aulas;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data
        {
            get
            {
                return _Data;
            }
            set
            {
                if (_Data != value)
                {
                    OnDataChanging(value);
                    ReportPropertyChanging("Data");
                    _Data = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Data");
                    OnDataChanged();
                }
            }
        }
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Horário
        {
            get
            {
                return _Horário;
            }
            set
            {
                if (_Horário != value)
                {
                    OnHorárioChanging(value);
                    ReportPropertyChanging("Horário");
                    _Horário = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Horário");
                    OnHorárioChanged();
                }
            }
        }
        private global::System.String _Horário;
        partial void OnHorárioChanging(global::System.String value);
        partial void OnHorárioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Atividade
        {
            get
            {
                return _Atividade;
            }
            set
            {
                if (_Atividade != value)
                {
                    OnAtividadeChanging(value);
                    ReportPropertyChanging("Atividade");
                    _Atividade = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Atividade");
                    OnAtividadeChanged();
                }
            }
        }
        private global::System.String _Atividade;
        partial void OnAtividadeChanging(global::System.String value);
        partial void OnAtividadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Turma
        {
            get
            {
                return _Turma;
            }
            set
            {
                if (_Turma != value)
                {
                    OnTurmaChanging(value);
                    ReportPropertyChanging("Turma");
                    _Turma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Turma");
                    OnTurmaChanged();
                }
            }
        }
        private global::System.Int32 _Turma;
        partial void OnTurmaChanging(global::System.Int32 value);
        partial void OnTurmaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Disciplina
        {
            get
            {
                return _Disciplina;
            }
            set
            {
                if (_Disciplina != value)
                {
                    OnDisciplinaChanging(value);
                    ReportPropertyChanging("Disciplina");
                    _Disciplina = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Disciplina");
                    OnDisciplinaChanged();
                }
            }
        }
        private global::System.String _Disciplina;
        partial void OnDisciplinaChanging(global::System.String value);
        partial void OnDisciplinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Professor
        {
            get
            {
                return _Professor;
            }
            set
            {
                if (_Professor != value)
                {
                    OnProfessorChanging(value);
                    ReportPropertyChanging("Professor");
                    _Professor = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Professor");
                    OnProfessorChanged();
                }
            }
        }
        private global::System.String _Professor;
        partial void OnProfessorChanging(global::System.String value);
        partial void OnProfessorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AulaId
        {
            get
            {
                return _AulaId;
            }
            set
            {
                if (_AulaId != value)
                {
                    OnAulaIdChanging(value);
                    ReportPropertyChanging("AulaId");
                    _AulaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AulaId");
                    OnAulaIdChanged();
                }
            }
        }
        private global::System.Guid _AulaId;
        partial void OnAulaIdChanging(global::System.Guid value);
        partial void OnAulaIdChanged();

        #endregion
    
    }

    #endregion
    
}
