//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace sparc.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SARCFACIN2Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SARCFACIN2Entities object using the connection string found in the 'SARCFACIN2Entities' section of the application configuration file.
        /// </summary>
        public SARCFACIN2Entities() : base("name=SARCFACIN2Entities", "SARCFACIN2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SARCFACIN2Entities object.
        /// </summary>
        public SARCFACIN2Entities(string connectionString) : base(connectionString, "SARCFACIN2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SARCFACIN2Entities object.
        /// </summary>
        public SARCFACIN2Entities(EntityConnection connection) : base(connection, "SARCFACIN2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sparc_Aulas> sparc_Aulas
        {
            get
            {
                if ((_sparc_Aulas == null))
                {
                    _sparc_Aulas = base.CreateObjectSet<sparc_Aulas>("sparc_Aulas");
                }
                return _sparc_Aulas;
            }
        }
        private ObjectSet<sparc_Aulas> _sparc_Aulas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sparc_Aulas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosparc_Aulas(sparc_Aulas sparc_Aulas)
        {
            base.AddObject("sparc_Aulas", sparc_Aulas);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SARCFACIN2Model", Name="sparc_Aulas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sparc_Aulas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sparc_Aulas object.
        /// </summary>
        /// <param name="horario">Initial value of the horario property.</param>
        /// <param name="atividade">Initial value of the atividade property.</param>
        /// <param name="turma">Initial value of the turma property.</param>
        /// <param name="disciplina">Initial value of the disciplina property.</param>
        /// <param name="categoria">Initial value of the categoria property.</param>
        public static sparc_Aulas Createsparc_Aulas(global::System.String horario, global::System.String atividade, global::System.Int32 turma, global::System.String disciplina, global::System.String categoria)
        {
            sparc_Aulas sparc_Aulas = new sparc_Aulas();
            sparc_Aulas.horario = horario;
            sparc_Aulas.atividade = atividade;
            sparc_Aulas.turma = turma;
            sparc_Aulas.disciplina = disciplina;
            sparc_Aulas.categoria = categoria;
            return sparc_Aulas;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String horario
        {
            get
            {
                return _horario;
            }
            set
            {
                if (_horario != value)
                {
                    OnhorarioChanging(value);
                    ReportPropertyChanging("horario");
                    _horario = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("horario");
                    OnhorarioChanged();
                }
            }
        }
        private global::System.String _horario;
        partial void OnhorarioChanging(global::System.String value);
        partial void OnhorarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String atividade
        {
            get
            {
                return _atividade;
            }
            set
            {
                if (_atividade != value)
                {
                    OnatividadeChanging(value);
                    ReportPropertyChanging("atividade");
                    _atividade = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("atividade");
                    OnatividadeChanged();
                }
            }
        }
        private global::System.String _atividade;
        partial void OnatividadeChanging(global::System.String value);
        partial void OnatividadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 turma
        {
            get
            {
                return _turma;
            }
            set
            {
                if (_turma != value)
                {
                    OnturmaChanging(value);
                    ReportPropertyChanging("turma");
                    _turma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("turma");
                    OnturmaChanged();
                }
            }
        }
        private global::System.Int32 _turma;
        partial void OnturmaChanging(global::System.Int32 value);
        partial void OnturmaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String disciplina
        {
            get
            {
                return _disciplina;
            }
            set
            {
                if (_disciplina != value)
                {
                    OndisciplinaChanging(value);
                    ReportPropertyChanging("disciplina");
                    _disciplina = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("disciplina");
                    OndisciplinaChanged();
                }
            }
        }
        private global::System.String _disciplina;
        partial void OndisciplinaChanging(global::System.String value);
        partial void OndisciplinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categoria
        {
            get
            {
                return _categoria;
            }
            set
            {
                if (_categoria != value)
                {
                    OncategoriaChanging(value);
                    ReportPropertyChanging("categoria");
                    _categoria = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("categoria");
                    OncategoriaChanged();
                }
            }
        }
        private global::System.String _categoria;
        partial void OncategoriaChanging(global::System.String value);
        partial void OncategoriaChanged();

        #endregion
    
    }

    #endregion
    
}
